# config/default.yaml
# Default configuration for PII Scanner

scanner:
  confidence_threshold: 0.5
  context_window: 50
  default_entities:
    - EMAIL_ADDRESS
    - PHONE_NUMBER
    - US_SSN
    - CREDIT_CARD
    - PERSON
  language: en
  max_text_length: 1000000
  max_file_size_mb: 50

logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: null  # Set to file path to enable file logging

api:
  host: 0.0.0.0
  port: 8000
  cors_enabled: true
  cors_origins:
    - "*"
  max_request_size_mb: 100

streamlit:
  host: 0.0.0.0
  port: 8501
  theme:
    primaryColor: "#FF6B6B"
    backgroundColor: "#FFFFFF"
    secondaryBackgroundColor: "#F0F2F6"

file_processing:
  supported_extensions:
    - .txt
    - .csv
    - .json
    - .log
    - .md
  max_batch_size: 100
  temp_dir: temp/